// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqT7N1PmJLGp8-FBTvKpDheEjOTCqiMk',
    appId: '1:66748875329:web:29bb4d26e5dd8dfaa0fcc0',
    messagingSenderId: '66748875329',
    projectId: 'gecho-6c1b7',
    authDomain: 'gecho-6c1b7.firebaseapp.com',
    storageBucket: 'gecho-6c1b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DwWb6gY2SwKH0VbtooGIXuHBSpJDu7Q',
    appId: '1:66748875329:android:21f5f83b44a1be6fa0fcc0',
    messagingSenderId: '66748875329',
    projectId: 'gecho-6c1b7',
    storageBucket: 'gecho-6c1b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpCNe0mr6rg9CgwWucOvu1r5z26M8L5I',
    appId: '1:66748875329:ios:ac14156d9921ae1da0fcc0',
    messagingSenderId: '66748875329',
    projectId: 'gecho-6c1b7',
    storageBucket: 'gecho-6c1b7.firebasestorage.app',
    iosBundleId: 'com.example.gecho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWpCNe0mr6rg9CgwWucOvu1r5z26M8L5I',
    appId: '1:66748875329:ios:ac14156d9921ae1da0fcc0',
    messagingSenderId: '66748875329',
    projectId: 'gecho-6c1b7',
    storageBucket: 'gecho-6c1b7.firebasestorage.app',
    iosBundleId: 'com.example.gecho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArqT7N1PmJLGp8-FBTvKpDheEjOTCqiMk',
    appId: '1:66748875329:web:dd033a3cdd9a326fa0fcc0',
    messagingSenderId: '66748875329',
    projectId: 'gecho-6c1b7',
    authDomain: 'gecho-6c1b7.firebaseapp.com',
    storageBucket: 'gecho-6c1b7.firebasestorage.app',
  );

}